project_id = "uvovskdrgagnbiwcxtlg"

[functions.philai-chat]
verify_jwt = true

[functions.paychangu-webhook]
verify_jwt = false

[functions.process-paychangu-payment]
verify_jwt = true

[functions.process-paypal-payment]
verify_jwt = true

[functions.process-stripe-payment]
verify_jwt = true

[functions.verify-payment]
verify_jwt = true

[functions.stripe-webhook]
verify_jwt = false
