project_id = "uvovskdrgagnbiwcxtlg"

[functions.philai-chat]
verify_jwt = false

[functions.process-paychangu-payment]
verify_jwt = false

[functions.process-paypal-payment]
verify_jwt = false

[functions.process-stripe-payment]
verify_jwt = false

[functions.verify-payment]
verify_jwt = false
